title: Linn Random Notes
theme: jekyll-theme-hacker
author: Aung Tun Linn
email: aungtunlinn1992@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Some of my random notes about electronics, embedded systems and programming will be saved here.
  Thanks for visiting my messy blog.
permalink: /:path
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
